apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-longhorn-vaultwarden
  namespace: example
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi